# © 2024 The Johns Hopkins University Applied Physics Laboratory LLC
# Development of this software was sponsored by the U.S. Government under 
# contracts no. 75D30120C07643, 75D30122C15442, 75D30124C19958

name: Scenario Detection App Phase 1
description: >
    The Scenario Detection Phase I application is designed to quickly explore the structured data fields—both demographic and diagnostic—available from syndromic data collected through the ESSENCE platform.

    The methods used in this application are inspired by the academic work of Li et al. (2023), ECOD: Unsupervised Outlier Detection Using Empirical Cumulative Distribution Functions (IEEE Transactions on Knowledge and Data Engineering, 35(12), 12181–12193). This research shows that for anomaly detection, examining each feature of a multivariate dataset independently is often both more accurate and efficient than more complex approaches.

    As a result, the main visualizations in the application represent the temporal anomalies for each feature individually. The application also provides interactive drill-down capabilities, enabling deeper investigation into the causes behind observed anomalies for any selected feature.
author: Joshua Kimrey & Catherine Schwartz
contributors: Gbedegnon Roseric Azondekon & Michael Sheppard
